#!/bin/bash

# mount the encrypted volume for vacuumlabs
vol_name=vacuumlabs
vol_uuid=261bc68a-0196-43e7-b082-8589a2763b83

sudo cryptsetup open UUID=$vol_uuid $vol_name
# enter the passphrase when asked for

mkdir -p ~/$vol_name
sudo mount /dev/mapper/$vol_name ~/$vol_name
