#!/bin/bash
# ssh -tY -L8083:localhost:8083 -L3000:localhost:3000 -L9630:localhost:9630 pcx "cd; exec fish -l"
# ssh -tY -L3009:localhost:3009 pcx "cd; exec fish -l"
# ssh -tY -L3010:localhost:3010 pcx "cd; exec fish -l"
# ssh -tY -L3013:localhost:3013 pcx "cd; exec fish -l"
ssh -tY \
    -L3000:localhost:3000 \
    -L3009:localhost:3009 \
    -L3010:localhost:3010 \
    -L3013:localhost:3013 \
    -L3014:localhost:3014 \
    -L3020:localhost:3020 \
    -L3021:localhost:3021 \
    -L3022:localhost:3022 \
    -L3023:localhost:3023 \
    -L3024:localhost:3024 \
    -L8083:localhost:8083 \
    -L9200:localhost:9200 \
    -L9630:localhost:9630 \
    pcx "cd; exec fish -l"
